### ISSUE TITLE
Links in Description are broken.

### ISSUE THREAD

**Issue by theperfectwill** [hexydec/tokenise#1]
@hexydec

The clickable links @ https://github.com/hexydec/tokenise#description need updated. They lead to blank pages for me. They seem to be the right links, but the protocol in them loads http, rather than https, and then results in a blank rendered browser page for me.

Just wanted to let you know.

**Comment by theperfectwill** [comment]
Update: They are missing the `.` before the `com` in them.

**Comment by hexydec** [comment]
Thanks mate, will fix.
